// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vepdsjixmtueadqesrjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlcGRzaml4bXR1ZWFkcWVzcmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjkxNTcsImV4cCI6MjA3MzU0NTE1N30.zsvkE1kEgRtk-8Sfxo_TkkKPuWuAtShwK-L04HlQHoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});